import { Controller, Post, Headers, ForbiddenException } from '@nestjs/common';
import { Public } from './common/decorators/public.decorator';
import { DataSource } from 'typeorm';
import { InjectDataSource } from '@nestjs/typeorm';

const TENANT = '00000000-0000-0000-0000-000000000001';

const SCHEDULE_X = [
  'ALPRAZOLAM','CLONAZEPAM','DIAZEPAM','LORAZEPAM','NITRAZEPAM',
  'TRIAZOLAM','MIDAZOLAM','ZOLPIDEM','ZOPICLONE','BROTIZOLAM',
  'MORPHINE','CODEINE','TRAMADOL','FENTANYL','BUPRENORPHINE',
  'OXYCODONE','HYDROCODONE','METHADONE','PENTAZOCINE','TAPENTADOL',
  'PHENOBARBITONE','PHENOBARBITAL','KETAMINE','THIOPENTAL',
  'METHYLPHENIDATE','AMPHETAMINE','DEXTROAMPHETAMINE',
];

const SCHEDULE_H1 = [
  'CIPROFLOXACIN','OFLOXACIN','LEVOFLOXACIN','MOXIFLOXACIN','NORFLOXACIN',
  'GATIFLOXACIN','SPARFLOXACIN','CEFIXIME','CEFTRIAXONE','CEFPODOXIME',
  'CEFUROXIME','CEFDINIR','CEFOPERAZONE','CEFEPIME','CEFTAZIDIME',
  'AZITHROMYCIN','CLARITHROMYCIN','ROXITHROMYCIN','ERYTHROMYCIN',
  'AMOXICILLIN','AMPICILLIN','CLOXACILLIN','AMOXYCLAV','AUGMENTIN',
  'MEROPENEM','IMIPENEM','ERTAPENEM','LINEZOLID','VANCOMYCIN',
  'RIFAMPICIN','ISONIAZID','ETHAMBUTOL','PYRAZINAMIDE',
  'ACYCLOVIR','OSELTAMIVIR','VALACYCLOVIR','FAMCICLOVIR',
  'FLUCONAZOLE','ITRACONAZOLE','VORICONAZOLE','POSACONAZOLE',
  'METRONIDAZOLE','TINIDAZOLE','ORNIDAZOLE','SECNIDAZOLE',
  'DOXYCYCLINE','TETRACYCLINE','MINOCYCLINE','CHLORAMPHENICOL',
  'COLISTIN','POLYMYXIN','FOSFOMYCIN','FAROPENEM',
];

const SCHEDULE_H = [
  'PREDNISOLONE','PREDNISONE','DEXAMETHASONE','BETAMETHASONE',
  'HYDROCORTISONE','METHYLPREDNISOLONE','TRIAMCINOLONE','BUDESONIDE',
  'BECLOMETHASONE','FLUTICASONE','MOMETASONE','CLOBETASOL',
  'INSULIN','GLIBENCLAMIDE','GLIMEPIRIDE','METFORMIN','GLICLAZIDE',
  'SITAGLIPTIN','VILDAGLIPTIN','EMPAGLIFLOZIN','DAPAGLIFLOZIN',
  'PIOGLITAZONE','AMLODIPINE','ATENOLOL','METOPROLOL','BISOPROLOL',
  'CARVEDILOL','ENALAPRIL','LISINOPRIL','RAMIPRIL','PERINDOPRIL',
  'TELMISARTAN','LOSARTAN','VALSARTAN','OLMESARTAN','CANDESARTAN',
  'NIFEDIPINE','DILTIAZEM','VERAPAMIL','FUROSEMIDE','SPIRONOLACTONE',
  'DIGOXIN','WARFARIN','CLOPIDOGREL','ATORVASTATIN','ROSUVASTATIN',
  'SIMVASTATIN','AMIODARONE','PHENYTOIN','CARBAMAZEPINE','VALPROATE',
  'LEVETIRACETAM','OXCARBAZEPINE','LAMOTRIGINE','GABAPENTIN','PREGABALIN',
  'HALOPERIDOL','RISPERIDONE','OLANZAPINE','QUETIAPINE','ARIPIPRAZOLE',
  'CLOZAPINE','FLUOXETINE','SERTRALINE','PAROXETINE','ESCITALOPRAM',
  'AMITRIPTYLINE','NORTRIPTYLINE','IMIPRAMINE','VENLAFAXINE','DULOXETINE',
  'OMEPRAZOLE','PANTOPRAZOLE','RABEPRAZOLE','ESOMEPRAZOLE','LANSOPRAZOLE',
  'DOMPERIDONE','METOCLOPRAMIDE','ONDANSETRON','MESALAZINE','SULFASALAZINE',
  'DICLOFENAC','IBUPROFEN','NAPROXEN','PIROXICAM','MELOXICAM',
  'CELECOXIB','ETORICOXIB','ACECLOFENAC','KETOROLAC','BACLOFEN',
  'TIZANIDINE','LEVOTHYROXINE','CARBIMAZOLE','PROPYLTHIOURACIL',
  'HYDROXYCHLOROQUINE','CHLOROQUINE','COLCHICINE','ALLOPURINOL','FEBUXOSTAT',
  'SILDENAFIL','TADALAFIL','ISOTRETINOIN','TRETINOIN',
  'TACROLIMUS','CYCLOSPORINE','MYCOPHENOLATE','AZATHIOPRINE','METHOTREXATE',
];

@Controller('admin')
export class ScheduleClassifierController {
  constructor(@InjectDataSource() private ds: DataSource) {}

  @Public()
  @Post('classify-schedules')
  async classify(@Headers('x-admin-key') key: string) {
    if (key !== 'medisyn-import-2024') throw new ForbiddenException();

    const medicines = await this.ds.query(
      `SELECT id, brand_name FROM medicines WHERE tenant_id = $1`, [TENANT]
    );

    let x = 0, h1 = 0, h = 0, otc = 0;

    for (const med of medicines) {
      const name = med.brand_name.toUpperCase();
      let schedule = 'OTC';

      if (SCHEDULE_X.some((k: string) => name.includes(k))) {
        schedule = 'X'; x++;
      } else if (SCHEDULE_H1.some((k: string) => name.includes(k))) {
        schedule = 'H1'; h1++;
      } else if (SCHEDULE_H.some((k: string) => name.includes(k))) {
        schedule = 'H'; h++;
      } else {
        otc++;
      }

      await this.ds.query(
        `UPDATE medicines SET schedule_class = $1, updated_at = NOW() WHERE id = $2`,
        [schedule, med.id]
      );
    }

    return {
      status: 'success',
      total: medicines.length,
      schedule_X: x,
      schedule_H1: h1,
      schedule_H: h,
      OTC: otc,
    };
  }
}
